### ISSUE TITLE
Offer project as JKI VI package

### ISSUE THREAD

**Issue by McGeifer** [samangh/wamplv#1]
Hello!

I was searching for a WAMP implementation for LabVIEW when I stumbled across this repository. I was trying to get it working but there are a lot of problems with missing dependencies (Websocket and JSON pack installed) to rather uncommon directories (extravilib ?). Also manually copying the files to the vi.lib is nothing I want to do for a project.

Since wamplv already uses JKI VI packages, it would be quite obvious to distribute the project as a VI package as well. This would be a lot more convenient and a lot less error prone.

At the moment I can't get it to run.

best regards
Jens

**Comment by samangh** [comment]
Hi Jens,

Thanks for giving _wamplv_ a try and your feedback. I think you are the first person to try it. 

Creating a VI package is definitely on my to do list and I plan on doing so once WAMP _callee_ features have been added (work in progress, won't take long). In the meanwhile, you should be able to clone _wamplv_ anywhere on your system. I suggest cloning the repo in _usr.lib_ for now, because that way the VI paths won't change.

The WebSocket and JDP JSON dependencies are loaded from the usual _<vi.lib>_ location. The dependency on VIs located in <_extravilib_> comes from use of LabVIEW data channels. If you are having issues with those then this [article](https://knowledge.ni.com/KnowledgeArticleDetails?id=kA03q000000YQgfCAG&l=en-GB) might help?

Best,
Saman

**Comment by McGeifer** [comment]
Hey!

Thanks for the link, gonna take a look at it 👍

**Comment by samangh** [comment]
Hello @McGeifer

I'm happy to say that the library is now available as a VIP package. You can download it immidiately from the [releases](https://github.com/samangh/wamplv/releases) page.

I've submitted the package to VIPM community repo, hopefully it should become available there too.
